Added virtualenv, fixed bootstrap procedure

diff --git a/site-bootstrap b/site-bootstrap
--- a/site-bootstrap
+++ b/site-bootstrap
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+me=site-bootstrap
+
 PYTHON_OPTIONS="-B"
 
 git submodule init || {
@@ -12,5 +14,22 @@ git submodule update || {
     exit 1
 }
 
+python build-aux/virtualenv/virtualenv.py build-aux/environment || {
+    echo "$me: cannot build the virtual environment"
+    exit 1
+}
+
+source build-aux/environment/bin/activate || {
+    echo "$me: cannot activate the virtual environment"
+    exit 1
+}
+
+python django/setup.py install || {
+    echo "$me: cannot install django into the environment"
+    exit 1
+}
+
 (cd project && rm -f database.db)                       || exit 1
 (cd project && python $PYTHON_OPTIONS manage.py syncdb) || exit 1
+
+exit 0
diff --git a/site-run b/site-run
--- a/site-run
+++ b/site-run
@@ -1,5 +1,17 @@
 #!/bin/sh
 
+me=site-run
+
 PYTHON_OPTIONS="-B"
 
-(cd project && python $PYTHON_OPTIONS manage.py runserver) || exit 1
+source build-aux/environment/bin/activate || {
+    echo "$me: cannot activate the environment"
+    exit 1
+}
+
+(cd project && python $PYTHON_OPTIONS manage.py runserver) || {
+    echo "$me: cannot run the server"
+    exit 1
+}
+
+exit 0
